apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    apps: zotprime-ingress-websocket
  name: zotprime-ingress-websocket
  namespace: zotprime
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cloud.google.com/load-balancer-type: "External"
    kubernetes.io/ingress.class: "gce"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
#    nginx.ingress.kubernetes.io/configuration-snippet: |
#       proxy_http_version 1.1;
#       proxy_set_header Upgrade "websocket";
#       proxy_set_header Connection "Upgrade";
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Connection "upgrade";
        proxy_cache_bypass $http_upgrade;
      }
spec:
  rules:
    - host: stream.projectdev.net
      http:
        paths:
          - backend:
              service:
                name: streamserver
                port:
                  name: streamserver
#                  number: 8081
#            pathType: Exact
            path: /
            pathType: Prefix