version: '3.9'
services:
  zotprime-db:
    image: "zotprime-db:${VER}"
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQLROOTPASSWORD}
      - MARIADB_DATABASE=${MYSQLDATABASE}
      - MARIADB_USER=${MYSQLUSER}
      - MARIADB_PASSWORD=${MYSQLPASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
  zotprime-elasticsearch:
    image: "zotprime-elasticsearch:${VER}"
    mem_limit: 2G
    mem_reservation: 1G
    build:
      context: .
      dockerfile: es.Dockerfile
    environment:
      - cluster.name=zotero
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false 
      - discovery.type=single-node
    volumes:
      - /etc/localtime:/etc/localtime:ro
  zotprime-redis:
    image: "zotprime-redis:${VER}"
    build:
      context: .
      dockerfile: r.Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
  zotprime-memcached:
    image: "zotprime-memcached:${VER}"
    build:
      context: .
      dockerfile: m.Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
  zotprime-localstack:
    image: "zotprime-localstack:${VER}"
    build:
      context: .
      dockerfile: ls.Dockerfile
    environment:
      - SERVICES=sns,sqs,apigateway
    volumes:
      - /etc/localtime:/etc/localtime:ro
  zotprime-minio:
    image: "zotprime-minio:${VER}"
    build:
      context: .
      dockerfile: minio.Dockerfile
    environment:
      - MINIO_ROOT_USER=${MINIOROOTUSER}
      - MINIO_ROOT_PASSWORD=${MINIOROOTPASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9001:9001"
    volumes:
      - /etc/localtime:/etc/localtime:ro
  zotprime-miniomc:
    image: "zotprime-miniomc:${VER}"
    build:
      context: .
      dockerfile: miniomc.Dockerfile
    entrypoint: >
         /bin/sh -c "
         /usr/bin/mc config host add minio http://zotprime-minio:9000 ${MINIOROOTUSER} ${MINIOROOTPASSWORD}; 
         exec mc admin trace -v -a minio;
         "
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - zotprime-minio
  zotprime-dataserver:
    image: "zotprime-dataserver:${VER}"
    build:
      context: .
      dockerfile: ds.Dockerfile
    ports:
      - "8080:80"
      - "8082:8082"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - RUN_USER=apache
      - RUN_GROUP=apache
    depends_on:
      - zotprime-db
      - zotprime-elasticsearch
      - zotprime-redis
      - zotprime-memcached 
      - zotprime-tinymceclean
      - zotprime-streamserver
    links:
      - zotprime-db:mysql
      - zotprime-elasticsearch:elasticsearch
      - zotprime-redis:redis
      - zotprime-memcached:memcached
      - zotprime-localstack:localstack
      - zotprime-minio:minio
      - zotprime-tinymceclean:tinymceclean
      - zotprime-streamserver:streamserver
    restart: always
  zotprime-tinymceclean:
    image: "zotprime-tinymceclean:${VER}"
    build:
      context: .
      dockerfile: tmcs.Dockerfile
    depends_on:
      - zotprime-db
      - zotprime-elasticsearch
      - zotprime-redis
      - zotprime-memcached
    links:
      - zotprime-redis:redis 
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
  zotprime-streamserver:
    image: "zotprime-streamserver:${VER}"
    build:
      context: .
      dockerfile: sts.Dockerfile
    ports:
      - "8081:81"
    volumes:
      - "./docker/stream-server/default.js:/usr/src/app/config/default.js:ro"
      - /etc/localtime:/etc/localtime:ro
    restart: always
    depends_on:
      - zotprime-db
      - zotprime-elasticsearch
      - zotprime-redis
      - zotprime-memcached 
    links:
      - zotprime-redis:redis
  zotprime-phpmyadmin:
    image: "zotprime-phpmyadmin:${VER}"
    build:
      context: .
      dockerfile: pa.Dockerfile
    ports:
      - "8083:80"
    environment:
      - PMA_HOST=mysql
    links:
      - zotprime-db:mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
volumes:
  dbdata:
   driver: local

