version: '3.9'
services:
  zotprime-db:
    image: mariadb:10
#    image: mysql:5.6
    restart: always
#    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLROOTPASSWORD}
      - MYSQL_DATABASE=${MYSQLDATABASE}
      - MYSQL_USER=${MYSQLUSER}
      - MYSQL_PASSWORD=${MYSQLPASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
#    ulimits:
#      nofile:
#         soft: 262144
#         hard: 262144
  zotprime-elasticsearch:
#   image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - cluster.name=zotero
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false 
       #     - cluster.routing.allocation.disk.watermark.flood_stage=500mb
      - discovery.type=single-node
    volumes:
      - /etc/localtime:/etc/localtime:ro
#   privileged: true
   #user: root
   #command: "sysctl -w vm.max_map_count=262144 && su elasticsearch -c bin/elasticsearch"
 #  sysctls:
 #           - vm.max_map_count=262144
#   command: "sysctl -w vm.max_map_count=262144"
  zotprime-redis:
    image: redis:5.0
 #   privileged: true
 #    user: root
 #    sysctls:
 #      - sysctl vm.overcommit_memory=1
    volumes:
      - /etc/localtime:/etc/localtime:ro
  zotprime-memcached:
    image: memcached:1.5
    volumes:
      - /etc/localtime:/etc/localtime:ro
  zotprime-localstack:
    image: atlassianlabs/localstack
    environment:
      - SERVICES=sns,sqs,apigateway
    volumes:
      - /etc/localtime:/etc/localtime:ro
  zotprime-minio:
#    image: minio/minio:RELEASE.2018-10-25T01-27-03Z
#    image: minio/minio:RELEASE.2019-01-31T00-31-19Z
#    image: minio/minio:RELEASE.2021-06-14T01-29-23Z
#    image: minio/minio:RELEASE.2021-10-02T16-31-05Z
    image: minio/minio
    environment:
#      - MINIO_ACCESS_KEY=zotero
#      - MINIO_SECRET_KEY=zoterodocker
#      - MINIO_HTTP_TRACE=/dev/stderr
      - MINIO_ROOT_USER=${MINIOROOTUSER}
      - MINIO_ROOT_PASSWORD=${MINIOROOTPASSWORD}
#    command: server /data
    command: server /data --console-address ":9001"
    ports:
#      - "8082:9000"
      - "9001:9001"
    volumes:
      - /etc/localtime:/etc/localtime:ro
  zotprime-miniomc:
    image: minio/mc
#    entrypoint:
#      - /bin/sh
    entrypoint: >
         /bin/sh -c "
         /usr/bin/mc config host add minio http://zotprime-minio:9000 ${MINIOROOTUSER} ${MINIOROOTPASSWORD}; 
         exec mc admin trace -v -a minio;
         "
#          exec sleep inf;
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - zotprime-minio
  zotprime-dataserver:
    image: zotprime-dataserver
    build:
      context: .
      dockerfile: ds.Dockerfile
#    extra_hosts:
#      - "zotero.localhost:127.0.0.1"
#      - "zotero-fulltext.localhost:127.0.0.1"
    ports:
      - "8080:80"
      - "8082:8082"
#      - "9000:9000"
    volumes:
      - "./dataserver/:/var/www/zotero:rw"
      - "./Zend/:/var/www/zotero/include/Zend:rw"
      - "./docker/dataserver/create-user.sh:/var/www/zotero/admin/create-user.sh:ro" 
      - "./docker/dataserver/config.inc.php:/var/www/zotero/include/config/config.inc.php:ro"
      - "./docker/dataserver/dbconnect.inc.php:/var/www/zotero/include/config/dbconnect.inc.php:ro"
      - "./docker/dataserver/header.inc.php:/var/www/zotero/include/header.inc.php:ro"
      - "./docker/dataserver/Storage.inc.php:/var/www/zotero/model/Storage.inc.php:ro"    
#      - "./docker/dataserver/config/FullText.inc.php:/var/www/zotero/model/FullText.inc.php:ro"     # DEBUG
      - "./docker/db/init-mysql.sh:/var/www/zotero/misc/init-mysql.sh:ro"
      - "./docker/db/db_update.sh:/var/www/zotero/misc/db_update.sh:ro"
      - "./docker/db/www.sql:/var/www/zotero/misc/www.sql:ro"
      - "./docker/db/shard.sql:/var/www/zotero/misc/shard.sql:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - RUN_USER=apache
      - RUN_GROUP=apache
    depends_on:
      - zotprime-db
      - zotprime-elasticsearch
      - zotprime-redis
      - zotprime-memcached 
      - zotprime-tinymceclean
      - zotprime-streamserver
    links:
      - zotprime-db:mysql
      - zotprime-elasticsearch:elasticsearch
      - zotprime-redis:redis
      - zotprime-memcached:memcached
      - zotprime-localstack:localstack
      - zotprime-minio:minio
      - zotprime-tinymceclean:tinymceclean
      - zotprime-streamserver:streamserver
    restart: always
  zotprime-tinymceclean:
    image: zotprime-tinymceclean
    build:
      context: .
      dockerfile: tmcs.Dockerfile
    depends_on:
      - zotprime-db
      - zotprime-elasticsearch
      - zotprime-redis
      - zotprime-memcached
    links:
      - zotprime-redis:redis 
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
  zotprime-streamserver:
    image: zotprime-streamserver
    build:
      context: .
      dockerfile: sts.Dockerfile
    ports:
      - "8081:81"
    volumes:
      - "./docker/stream-server/default.js:/usr/src/app/config/default.js:ro"
      - /etc/localtime:/etc/localtime:ro
    restart: always
    depends_on:
      - zotprime-db
      - zotprime-elasticsearch
      - zotprime-redis
      - zotprime-memcached 
    links:
      - zotprime-redis:redis
  zotprime-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8083:80"
    environment:
      - PMA_HOST=mysql
    links:
      - zotprime-db:mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro

volumes:
  dbdata:
   driver: local

