version: '3.9'
services:
  db-zotero-mysql:
    image: mariadb:10
   # command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLROOTPASSWORD}
      - MYSQL_DATABASE=${MYSQLDATABASE}
      - MYSQL_USER=${MYSQLUSER}
      - MYSQL_PASSWORD=${MYSQLPASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
  db-zotero-elasticsearch:
#   image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
   image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
   environment:
     - cluster.name=zotero
     - xpack.security.enabled=false
     - cluster.routing.allocation.disk.threshold_enabled=false 
       #     - cluster.routing.allocation.disk.watermark.flood_stage=500mb
     - discovery.type=single-node
#   privileged: true
   #user: root
   #command: "sysctl -w vm.max_map_count=262144 && su elasticsearch -c bin/elasticsearch"
 #  sysctls:
 #           - vm.max_map_count=262144
#   command: "sysctl -w vm.max_map_count=262144"
  db-zotero-redis:
     image: redis:5.0
  db-zotero-memcached:
     image: memcached:1.5
  db-zotero-localstack:
    image: atlassianlabs/localstack
    environment:
      - SERVICES=sns,sqs,apigateway
  db-zotero-minio:
    image: minio/minio
    build:
      context: ./minio
    environment:
      - MINIO_ACCESS_KEY=zotero
      - MINIO_SECRET_KEY=zoterodocker
    command: server /data
  app-zotero:
    image: app-zotero
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:81"
      - "8082:8082"
    volumes:
      - "../:/var/www/zotero:rw"
      - "./config/config.inc.php:/var/www/zotero/include/config/config.inc.php:ro"
      - "./config/dbconnect.inc.php:/var/www/zotero/include/config/dbconnect.inc.php:ro"
      - "./config/default.js:/var/www/zotero/stream-server/config/default.js:ro"
    environment:
      - RUN_USER=www-data
      - RUN_GROUP=www-data
    depends_on:
      - db-zotero-mysql
      - db-zotero-elasticsearch
      - db-zotero-redis
      - db-zotero-memcached 
    links:
      - db-zotero-mysql:mysql
      - db-zotero-elasticsearch:elasticsearch
      - db-zotero-redis:redis
      - db-zotero-memcached:memcached
      - db-zotero-localstack:localstack
      - db-zotero-minio:minio
    restart: always
  app-zotero-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8083:80"
    environment:
      - PMA_HOST=mysql
    links:
      - db-zotero-mysql:mysql

volumes:
  dbdata:
   driver: local

