
---
apiVersion: apps/v1
kind: Deployment
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: app-zotprime
    name: app-zotprime
spec:
    replicas: {{ index .Values "common" "replicas" }}
    selector:
        matchLabels:
            move2kube.konveyor.io/service: app-zotprime
    strategy: {}
    template:
        metadata:
            creationTimestamp: null
            labels:
                move2kube.konveyor.io/service: app-zotprime
            name: app-zotprime
        spec:
            containers:
                - image: localhost:32000/zotprime-k8s/app-zotprime:latest
                  imagePullPolicy: Always
                  name: app-zotprime
                  ports:
                    - containerPort: 8080
                  resources: {}
            restartPolicy: Always
            securityContext: {}
status: {}

...
