apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: db-zotprime-minio
  name: db-zotprime-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      move2kube.konveyor.io/service: db-zotprime-minio
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: db-zotprime-minio
      name: db-zotprime-minio
    spec:
      containers:
        - image: localhost:32000/zotprime-k8s/db-zotprime-minio:latest
          imagePullPolicy: Always
          name: db-zotprime-minio
          ports:
            - containerPort: 9000
          resources: {}
      restartPolicy: Always
      securityContext: {}
status: {}
