apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: db-zotprime-minio
  name: db-zotprime-minio
spec:
#  ports:
#    - name: port-8080
#      port: 8080
#      targetPort: 8080
  selector:
    move2kube.konveyor.io/service: db-zotprime-minio
  type: ClusterIP
status:
  loadBalancer: {}
