apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: zotprime-k8s
  name: zotprime-k8s
spec:
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              service:
                name: zotprime-streamserver
                port:
                  name: port-8081
            path: /stream-server
            pathType: Prefix
#          - backend:
#              service:
#                name: zotprime-tinymceclean
#                port:
#                  name: port-16342
#            path: /zotprime-tinymceclean
#            pathType: Prefix
#          - backend:
#              service:
#                name: zotprime-minio
#                port:
#                  name: port-8080
#            path: /
#            pathType: Prefix
          - backend:
              service:
                name: zotprime-dataserver
                port:
                  name: port-8080
            path: /
            pathType: Prefix
status:
  loadBalancer: {}
