name: Client Test Build 

on:
  push:
    paths:
      - client/**
      - clientbuildtest.Dockerfile
      - .github/workflows/client-build-test.yml
    branches: [ "development" ]

  pull_request:
    branches: [ "development" ]
    paths:
      - client/**
      - clientbuildtest.Dockerfile
      - .github/workflows/client-build-test.yml
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Client
      run: DOCKER_BUILDKIT=1 docker build . --file clientbuildtest.Dockerfile --output build --tag client:$(date +%s)