name: Streamserver Image CI

on:
  push:
    paths:
      - stream-server/**
      - docker/stream-server/**
      - .github/workflows/streamserver-image.yml
    branches: [ "development" ]

  pull_request:
    branches: [ "development" ]
    paths:
      - stream-server/**
      - docker/stream-server/**
      - .github/workflows/streamserver-image.yml


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout submodules
      run: git submodule update --init stream-server
    - name: Build the Docker image
#      working-directory: ./stream-server
      run: docker build . --file sts.Dockerfile --tag zotprime-streamserver:$(date +%s)
#      uses: docker/build-push-action@v2
#      with:
#        context: .
#        file: Dockerfile
